### ISSUE TITLE
Peer dependencies required to install

### ISSUE THREAD

**Issue by Nishit-Chauhan** [yashtops/react-native-cubetap#2]
Hello @yashtops 
installed Cubetap SDK all peer dependancy are installed in node_modules, but i have to install following dependency to separately use the sdk otherwise it throws native error.

` npm install react-native-bluetooth-classic @react-native-async-storage/async-storage react-native-fs react-native-geolocation-service`

can you please check if we can fix this.

**Comment by yashtops** [comment]
Fixed in [v1.0.4](https://github.com/yashtops/react-native-cubetap)
